Public Class frm_reporte_orden

    Private Sub frm_reporte_orden_Load(sender As System.Object, e As System.EventArgs) Handles MyBase.Load
        Dim dt As New DataS_Reportes
        For Each dr As DataGridViewRow In frm_listado_orden_trabajo_ampliada.dgv_detalle_orden.Rows
            dt.DT_Orden.AddDT_OrdenRow(dr.Cells("ORT_id_orden_trabajo").Value,
                                       dr.Cells("ORT_tipo_ot").Value,
                                       dr.Cells("ORT_numero_ot").Value,
                                       dr.Cells("ORT_observaciones_ot").Value,
                                       dr.Cells("ORT_mejoras_ot").Value,
                                       dr.Cells("VEN_id_vendedor").Value,
                                       dr.Cells("VEN_nombre_ven").Value,
                                       dr.Cells("VEN_apellido_ven").Value,
                                       dr.Cells("ORT_fecha_ot").Value,
                                       dr.Cells("ORT_fecha_entrega").Value,
                                       dr.Cells("CLI_id_cliente").Value,
                                       dr.Cells("CLI_razon_social").Value,
                                       dr.Cells("CLI_domicilio").Value,
                                       dr.Cells("PIE_id_pieza").Value,
                                       dr.Cells("PIE_id_pieza_offset").Value,
                                       dr.Cells("PIE_nombre_pie").Value,
                                       dr.Cells("PIE_ubicacion").Value,
                                       dr.Cells("id_detalle_orden_trabajo").Value,
                                       dr.Cells("DOT_cantidad_producto").Value,
                                       dr.Cells("DOT_tamaño_producto").Value,
                                       dr.Cells("DOT_tipo_impresion_dot").Value,
                                       dr.Cells("DOT_papel_soporte_1").Value,
                                       dr.Cells("DOT_papel_soporte_2").Value,
                                       dr.Cells("DOT_papel_soporte_3").Value,
                                       dr.Cells("DOT_gramaje_soporte_1").Value,
                                       dr.Cells("DOT_gramaje_soporte_2").Value,
                                       dr.Cells("DOT_gramaje_soporte_3").Value,
                                       dr.Cells("DOT_cantidad_soporte_1").Value,
                                       dr.Cells("DOT_cantidad_soporte_2").Value,
                                       dr.Cells("DOT_cantidad_soporte_3").Value,
                                       dr.Cells("DOT_formato_soporte_1").Value,
                                       dr.Cells("DOT_formato_soporte_2").Value,
                                       dr.Cells("DOT_formato_soporte_3").Value,
                                       dr.Cells("cantidad_1_PM_offset").Value,
                                       dr.Cells("cantidad_2_PM_offset").Value,
                                       dr.Cells("cantidad_3_PM_offset").Value,
                                       dr.Cells("formato_1_PM_offset").Value,
                                       dr.Cells("formato_2_PM_offset").Value,
                                       dr.Cells("formato_3_PM_offset").Value,
                                       dr.Cells("modo_impresion_offset").Value,
                                       dr.Cells("tipo_impresion_offset").Value,
                                       dr.Cells("chapas_soporte1_offset").Value,
                                       dr.Cells("chapas_soporte2_offset").Value,
                                       dr.Cells("chapas_soporte3_offset").Value,
                                       dr.Cells("impresora_offset").Value,
                                       dr.Cells("marca_offset").Value,
                                       dr.Cells("cantidad_1_PM_digital").Value,
                                       dr.Cells("cantidad_2_PM_digital").Value,
                                       dr.Cells("cantidad_3_PM_digital").Value,
                                       dr.Cells("formato_1_PM_digital").Value,
                                       dr.Cells("formato_2_PM_digital").Value,
                                       dr.Cells("formato_3_PM_digital").Value,
                                       dr.Cells("modo_impresion_digital").Value,
                                       dr.Cells("tipo_impresion_digital").Value,
                                       dr.Cells("dato_variable").Value,
                                       dr.Cells("Expr1").Value,
                                       dr.Cells("cantidad_gran_formato").Value,
                                       dr.Cells("tamaño_gran_formato").Value,
                                       dr.Cells("sustrato_gran_formato").Value,
                                       dr.Cells("calidad_gran_formato").Value,
                                       dr.Cells("sistema_gran_formato").Value,
                                       dr.Cells("tipo_terminacion").Value,
                                       dr.Cells("descripcion_terminacion").Value)
        Next
        Dim rptdoc As CrystalDecisions.CrystalReports.Engine.ReportDocument
        rptdoc = New rpt_orden
        rptdoc.SetDataSource(dt)
        CrystalReportViewer1.ReportSource = rptdoc
    End Sub
End Class